import pusmmeDataReducer from 'viewManager/PUSMMEView/store/dataReducer';
import { INJECT_PUS_DATA } from '../../../store/types';

describe('viewManager/PUSMMEView/store/dataReducer', () => {
  it('should replace constants', () => {
    const state = {
      PUSMMEViewData: {},
    };
    const action = {
      type: INJECT_PUS_DATA,
      payload: {
        data: {
          PUSMMEView: {
            pusMmeModel: {
              groundDate: 1531404578453,
              pusMmePacket: [
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 2,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 2,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 2,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 1,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 1,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 1,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 2,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 2,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 1,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
                {
                  collectionInterval: 'myString',
                  forwardingStatusRidSid: 100,
                  forwardingStatusTypeSubtype: 1,
                  generationMode: 'myString',
                  lastUpdateModeCollectInterval: 100,
                  lastUpdateModeFwdStatusTypeRidSid: 100,
                  lastUpdateModeFwdStatusTypeSubtype: 1,
                  lastUpdateModeGenMode: 1,
                  lastUpdateModeSid: 100,
                  lastUpdateModeStatus: 1,
                  lastUpdateModeSubSamplingRatio: 1,
                  lastUpdateModeValidParamExpValue: 100,
                  lastUpdateModeValidParamId: 100,
                  lastUpdateModeValidParamMask: 100,
                  lastUpdateTimeCollectInterval: 1531404578453,
                  lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                  lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                  lastUpdateTimeGenMode: 1531404578453,
                  lastUpdateTimeSid: 1531404578453,
                  lastUpdateTimeStatus: 1531404578453,
                  lastUpdateTimeSubSamplingRatio: 1531404578453,
                  lastUpdateTimeValidParamExpValue: 1531404578453,
                  lastUpdateTimeValidParamId: 1531404578453,
                  lastUpdateTimeValidParamMask: 1531404578453,
                  packetApid: 100,
                  packetApidName: 'myString',
                  packetName: 'myString',
                  packetType: 'myString',
                  pusMmePacketParameter: [
                    {
                      lastUpdateModeFilteredStatus: 1,
                      lastUpdateModeStoreId: 1,
                      lastUpdateTimeFilteredStatus: 1531404578453,
                      lastUpdateTimeStoreId: 1531404578453,
                      parameterFilteredStatus: 'myString',
                      parameterId: 1,
                      parameterName: 'myString',
                      parameterOrder: 1,
                      uniqueId: 1,
                    },
                  ],
                  pusMmePacketStore: [
                    {
                      lastUpdateModeStoreId: 1,
                      lastUpdateModeStoreStatus: 1,
                      lastUpdateModeSubSamplingRatio: 1,
                      lastUpdateTimeStoreId: 1531404578453,
                      lastUpdateTimeStoreStatus: 1531404578453,
                      lastUpdateTimeSubSamplingRatio: 1531404578453,
                      storeId: 1,
                      storeName: 'myString',
                      storeStatus: 1,
                      subSamplingRatio: 1,
                      uniqueId: 1,
                    },
                  ],
                  serviceApid: 100,
                  serviceApidName: 'myString',
                  sid: 100,
                  sidLabel: 'myString',
                  status: 1,
                  subsamplingRatio: 1,
                  uniqueId: 100,
                  validityParameterExpectedValue: 'myString',
                  validityParameterId: 100,
                  validityParameterMask: 'myString',
                  validityParameterName: 'myString',
                },
              ],
              serviceApid: 100,
              serviceApidName: 'myString',
              status: 1,
              uniqueId: 1,
            },
          },
        },
      },
    };
    expect(pusmmeDataReducer(state, action)).toEqual(
      {
        PUSMMEViewData: {
          'ac3bb721-a113-4c8a-9917-55e8f0894625': {
            serviceApid: 100,
            status: 1,
            groundDate: 1531404578453,
            serviceApidName: 'myString',
            uniqueId: 1,
            pusMmePacket: [
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 2,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 2,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 2,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 1,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 1,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 1,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 2,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 2,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 1,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
              {
                collectionInterval: 'myString',
                forwardingStatusRidSid: 100,
                forwardingStatusTypeSubtype: 1,
                generationMode: 'myString',
                lastUpdateModeCollectInterval: 100,
                lastUpdateModeFwdStatusTypeRidSid: 100,
                lastUpdateModeFwdStatusTypeSubtype: 1,
                lastUpdateModeGenMode: 1,
                lastUpdateModeSid: 100,
                lastUpdateModeStatus: 1,
                lastUpdateModeSubSamplingRatio: 1,
                lastUpdateModeValidParamExpValue: 100,
                lastUpdateModeValidParamId: 100,
                lastUpdateModeValidParamMask: 100,
                lastUpdateTimeCollectInterval: 1531404578453,
                lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                lastUpdateTimeGenMode: 1531404578453,
                lastUpdateTimeSid: 1531404578453,
                lastUpdateTimeStatus: 1531404578453,
                lastUpdateTimeSubSamplingRatio: 1531404578453,
                lastUpdateTimeValidParamExpValue: 1531404578453,
                lastUpdateTimeValidParamId: 1531404578453,
                lastUpdateTimeValidParamMask: 1531404578453,
                packetApid: 100,
                packetApidName: 'myString',
                packetName: 'myString',
                packetType: 'myString',
                pusMmePacketParameter: [
                  {
                    lastUpdateModeFilteredStatus: 1,
                    lastUpdateModeStoreId: 1,
                    lastUpdateTimeFilteredStatus: 1531404578453,
                    lastUpdateTimeStoreId: 1531404578453,
                    parameterFilteredStatus: 'myString',
                    parameterId: 1,
                    parameterName: 'myString',
                    parameterOrder: 1,
                    uniqueId: 1,
                  },
                ],
                pusMmePacketStore: [
                  {
                    lastUpdateModeStoreId: 1,
                    lastUpdateModeStoreStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateTimeStoreId: 1531404578453,
                    lastUpdateTimeStoreStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    storeId: 1,
                    storeName: 'myString',
                    storeStatus: 1,
                    subSamplingRatio: 1,
                    uniqueId: 1,
                  },
                ],
                serviceApid: 100,
                serviceApidName: 'myString',
                sid: 100,
                sidLabel: 'myString',
                status: 1,
                subsamplingRatio: 1,
                uniqueId: 100,
                validityParameterExpectedValue: 'myString',
                validityParameterId: 100,
                validityParameterMask: 'myString',
                validityParameterName: 'myString',
              },
            ],
            tables: {
              packets: {
                data: [
                  {
                    collectionInterval: 'myString',
                    forwardingStatusRidSid: 100,
                    forwardingStatusTypeSubtype: 1,
                    generationMode: 'myString',
                    lastUpdateModeApid: '',
                    lastUpdateModeCollectInterval: 100,
                    lastUpdateModeFwdStatusTypeRidSid: 100,
                    lastUpdateModeFwdStatusTypeSubtype: 1,
                    lastUpdateModeGenMode: 1,
                    lastUpdateModeSid: 100,
                    lastUpdateModeStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateModeValidParamExpValue: 100,
                    lastUpdateModeValidParamId: 100,
                    lastUpdateModeValidParamMask: 100,
                    lastUpdateTimeCollectInterval: 1531404578453,
                    lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                    lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                    lastUpdateTimeGenMode: 1531404578453,
                    lastUpdateTimeSid: 1531404578453,
                    lastUpdateTimeStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    lastUpdateTimeValidParamExpValue: 1531404578453,
                    lastUpdateTimeValidParamId: 1531404578453,
                    lastUpdateTimeValidParamMask: 1531404578453,
                    packetApid: 100,
                    packetApidName: 'myString',
                    packetName: 'myString',
                    packetType: 'myString',
                    pusMmePacketParameter: [
                      {
                        lastUpdateModeFilteredStatus: 1,
                        lastUpdateModeStoreId: 1,
                        lastUpdateTimeFilteredStatus: 1531404578453,
                        lastUpdateTimeStoreId: 1531404578453,
                        parameterFilteredStatus: 'myString',
                        parameterId: 1,
                        parameterName: 'myString',
                        parameterOrder: 1,
                        uniqueId: 1,
                      },
                    ],
                    pusMmePacketStore: [
                      {
                        lastUpdateModeStoreId: 1,
                        lastUpdateModeStoreStatus: 1,
                        lastUpdateModeSubSamplingRatio: 1,
                        lastUpdateTimeStoreId: 1531404578453,
                        lastUpdateTimeStoreStatus: 1531404578453,
                        lastUpdateTimeSubSamplingRatio: 1531404578453,
                        storeId: 1,
                        storeName: 'myString',
                        storeStatus: 1,
                        subSamplingRatio: 1,
                        uniqueId: 1,
                      },
                    ],
                    serviceApid: 100,
                    serviceApidName: 'myString',
                    sid: 100,
                    sidLabel: 'myString',
                    status: 'ENABLED',
                    subsamplingRatio: 1,
                    uniqueId: 100,
                    validityParameterExpectedValue: 'myString',
                    validityParameterId: 100,
                    validityParameterMask: 'myString',
                    validityParameterName: 'myString',
                  },
                  {
                    collectionInterval: 'myString',
                    forwardingStatusRidSid: 100,
                    forwardingStatusTypeSubtype: 1,
                    generationMode: 'myString',
                    lastUpdateModeApid: '',
                    lastUpdateModeCollectInterval: 100,
                    lastUpdateModeFwdStatusTypeRidSid: 100,
                    lastUpdateModeFwdStatusTypeSubtype: 1,
                    lastUpdateModeGenMode: 1,
                    lastUpdateModeSid: 100,
                    lastUpdateModeStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateModeValidParamExpValue: 100,
                    lastUpdateModeValidParamId: 100,
                    lastUpdateModeValidParamMask: 100,
                    lastUpdateTimeCollectInterval: 1531404578453,
                    lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                    lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                    lastUpdateTimeGenMode: 1531404578453,
                    lastUpdateTimeSid: 1531404578453,
                    lastUpdateTimeStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    lastUpdateTimeValidParamExpValue: 1531404578453,
                    lastUpdateTimeValidParamId: 1531404578453,
                    lastUpdateTimeValidParamMask: 1531404578453,
                    packetApid: 100,
                    packetApidName: 'myString',
                    packetName: 'myString',
                    packetType: 'myString',
                    pusMmePacketParameter: [
                      {
                        lastUpdateModeFilteredStatus: 1,
                        lastUpdateModeStoreId: 1,
                        lastUpdateTimeFilteredStatus: 1531404578453,
                        lastUpdateTimeStoreId: 1531404578453,
                        parameterFilteredStatus: 'myString',
                        parameterId: 1,
                        parameterName: 'myString',
                        parameterOrder: 1,
                        uniqueId: 1,
                      },
                    ],
                    pusMmePacketStore: [
                      {
                        lastUpdateModeStoreId: 1,
                        lastUpdateModeStoreStatus: 1,
                        lastUpdateModeSubSamplingRatio: 1,
                        lastUpdateTimeStoreId: 1531404578453,
                        lastUpdateTimeStoreStatus: 1531404578453,
                        lastUpdateTimeSubSamplingRatio: 1531404578453,
                        storeId: 1,
                        storeName: 'myString',
                        storeStatus: 1,
                        subSamplingRatio: 1,
                        uniqueId: 1,
                      },
                    ],
                    serviceApid: 100,
                    serviceApidName: 'myString',
                    sid: 100,
                    sidLabel: 'myString',
                    status: 'ENABLED',
                    subsamplingRatio: 1,
                    uniqueId: 100,
                    validityParameterExpectedValue: 'myString',
                    validityParameterId: 100,
                    validityParameterMask: 'myString',
                    validityParameterName: 'myString',
                  },
                  {
                    collectionInterval: 'myString',
                    forwardingStatusRidSid: 100,
                    forwardingStatusTypeSubtype: 1,
                    generationMode: 'myString',
                    lastUpdateModeApid: '',
                    lastUpdateModeCollectInterval: 100,
                    lastUpdateModeFwdStatusTypeRidSid: 100,
                    lastUpdateModeFwdStatusTypeSubtype: 1,
                    lastUpdateModeGenMode: 1,
                    lastUpdateModeSid: 100,
                    lastUpdateModeStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateModeValidParamExpValue: 100,
                    lastUpdateModeValidParamId: 100,
                    lastUpdateModeValidParamMask: 100,
                    lastUpdateTimeCollectInterval: 1531404578453,
                    lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                    lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                    lastUpdateTimeGenMode: 1531404578453,
                    lastUpdateTimeSid: 1531404578453,
                    lastUpdateTimeStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    lastUpdateTimeValidParamExpValue: 1531404578453,
                    lastUpdateTimeValidParamId: 1531404578453,
                    lastUpdateTimeValidParamMask: 1531404578453,
                    packetApid: 100,
                    packetApidName: 'myString',
                    packetName: 'myString',
                    packetType: 'myString',
                    pusMmePacketParameter: [
                      {
                        lastUpdateModeFilteredStatus: 1,
                        lastUpdateModeStoreId: 1,
                        lastUpdateTimeFilteredStatus: 1531404578453,
                        lastUpdateTimeStoreId: 1531404578453,
                        parameterFilteredStatus: 'myString',
                        parameterId: 1,
                        parameterName: 'myString',
                        parameterOrder: 1,
                        uniqueId: 1,
                      },
                    ],
                    pusMmePacketStore: [
                      {
                        lastUpdateModeStoreId: 1,
                        lastUpdateModeStoreStatus: 1,
                        lastUpdateModeSubSamplingRatio: 1,
                        lastUpdateTimeStoreId: 1531404578453,
                        lastUpdateTimeStoreStatus: 1531404578453,
                        lastUpdateTimeSubSamplingRatio: 1531404578453,
                        storeId: 1,
                        storeName: 'myString',
                        storeStatus: 1,
                        subSamplingRatio: 1,
                        uniqueId: 1,
                      },
                    ],
                    serviceApid: 100,
                    serviceApidName: 'myString',
                    sid: 100,
                    sidLabel: 'myString',
                    status: 'ENABLED',
                    subsamplingRatio: 1,
                    uniqueId: 100,
                    validityParameterExpectedValue: 'myString',
                    validityParameterId: 100,
                    validityParameterMask: 'myString',
                    validityParameterName: 'myString',
                  },
                  {
                    collectionInterval: 'myString',
                    forwardingStatusRidSid: 100,
                    forwardingStatusTypeSubtype: 1,
                    generationMode: 'myString',
                    lastUpdateModeApid: '',
                    lastUpdateModeCollectInterval: 100,
                    lastUpdateModeFwdStatusTypeRidSid: 100,
                    lastUpdateModeFwdStatusTypeSubtype: 1,
                    lastUpdateModeGenMode: 1,
                    lastUpdateModeSid: 100,
                    lastUpdateModeStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateModeValidParamExpValue: 100,
                    lastUpdateModeValidParamId: 100,
                    lastUpdateModeValidParamMask: 100,
                    lastUpdateTimeCollectInterval: 1531404578453,
                    lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                    lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                    lastUpdateTimeGenMode: 1531404578453,
                    lastUpdateTimeSid: 1531404578453,
                    lastUpdateTimeStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    lastUpdateTimeValidParamExpValue: 1531404578453,
                    lastUpdateTimeValidParamId: 1531404578453,
                    lastUpdateTimeValidParamMask: 1531404578453,
                    packetApid: 100,
                    packetApidName: 'myString',
                    packetName: 'myString',
                    packetType: 'myString',
                    pusMmePacketParameter: [
                      {
                        lastUpdateModeFilteredStatus: 1,
                        lastUpdateModeStoreId: 1,
                        lastUpdateTimeFilteredStatus: 1531404578453,
                        lastUpdateTimeStoreId: 1531404578453,
                        parameterFilteredStatus: 'myString',
                        parameterId: 1,
                        parameterName: 'myString',
                        parameterOrder: 1,
                        uniqueId: 1,
                      },
                    ],
                    pusMmePacketStore: [
                      {
                        lastUpdateModeStoreId: 1,
                        lastUpdateModeStoreStatus: 1,
                        lastUpdateModeSubSamplingRatio: 1,
                        lastUpdateTimeStoreId: 1531404578453,
                        lastUpdateTimeStoreStatus: 1531404578453,
                        lastUpdateTimeSubSamplingRatio: 1531404578453,
                        storeId: 1,
                        storeName: 'myString',
                        storeStatus: 1,
                        subSamplingRatio: 1,
                        uniqueId: 1,
                      },
                    ],
                    serviceApid: 100,
                    serviceApidName: 'myString',
                    sid: 100,
                    sidLabel: 'myString',
                    status: 'ENABLED',
                    subsamplingRatio: 1,
                    uniqueId: 100,
                    validityParameterExpectedValue: 'myString',
                    validityParameterId: 100,
                    validityParameterMask: 'myString',
                    validityParameterName: 'myString',
                  },
                  {
                    collectionInterval: 'myString',
                    forwardingStatusRidSid: 100,
                    forwardingStatusTypeSubtype: 1,
                    generationMode: 'myString',
                    lastUpdateModeApid: '',
                    lastUpdateModeCollectInterval: 100,
                    lastUpdateModeFwdStatusTypeRidSid: 100,
                    lastUpdateModeFwdStatusTypeSubtype: 1,
                    lastUpdateModeGenMode: 1,
                    lastUpdateModeSid: 100,
                    lastUpdateModeStatus: 1,
                    lastUpdateModeSubSamplingRatio: 1,
                    lastUpdateModeValidParamExpValue: 100,
                    lastUpdateModeValidParamId: 100,
                    lastUpdateModeValidParamMask: 100,
                    lastUpdateTimeCollectInterval: 1531404578453,
                    lastUpdateTimeFwdStatusTypeRidSid: 1531404578453,
                    lastUpdateTimeFwdStatusTypeSubtype: 1531404578453,
                    lastUpdateTimeGenMode: 1531404578453,
                    lastUpdateTimeSid: 1531404578453,
                    lastUpdateTimeStatus: 1531404578453,
                    lastUpdateTimeSubSamplingRatio: 1531404578453,
                    lastUpdateTimeValidParamExpValue: 1531404578453,
                    lastUpdateTimeValidParamId: 1531404578453,
                    lastUpdateTimeValidParamMask: 1531404578453,
                    packetApid: 100,
                    packetApidName: 'myString',
                    packetName: 'myString',
                    packetType: 'myString',
                    pusMmePacketParameter: [
                      {
                        lastUpdateModeFilteredStatus: 1,
                        lastUpdateModeStoreId: 1,
                        lastUpdateTimeFilteredStatus: 1531404578453,
                        lastUpdateTimeStoreId: 1531404578453,
                        parameterFilteredStatus: 'myString',
                        parameterId: 1,
                        parameterName: 'myString',
                        parameterOrder: 1,
                        uniqueId: 1,
                      },
                    ],
                    pusMmePacketStore: [
                      {
                        lastUpdateModeStoreId: 1,
                        lastUpdateModeStoreStatus: 1,
                        lastUpdateModeSubSamplingRatio: 1,
                        lastUpdateTimeStoreId: 1531404578453,
                        lastUpdateTimeStoreStatus: 1531404578453,
                        lastUpdateTimeSubSamplingRatio: 1531404578453,
                        storeId: 1,
                        storeName: 'myString',
                        storeStatus: 1,
                        subSamplingRatio: 1,
                        uniqueId: 1,
                      },
                    ],
                    serviceApid: 100,
                    serviceApidName: 'myString',
                    sid: 100,
                    sidLabel: 'myString',
                    status: 'ENABLED',
                    subsamplingRatio: 1,
                    uniqueId: 100,
                    validityParameterExpectedValue: 'myString',
                    validityParameterId: 100,
                    validityParameterMask: 'myString',
                    validityParameterName: 'myString',
                  },
                ],
                keep: [
                  0,
                  1,
                  2,
                  3,
                  4,
                ],
              },
            },
          },
        },
      }
    );
  });
});
