
# - Try to find ConsumerParameter
# Once done this will define
#  GPCCHSEVISSTANDALONETIMEBAR_FOUND - System has GPCCHS-E-VIS STANDALONETIMEBAR
#  GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIRS - The GPCCHS-E-VIS STANDALONETIMEBAR include directories
#  GPCCHSEVISSTANDALONETIMEBAR_LIBRARIES - The libraries needed to use GPCCHS-E-VIS STANDALONETIMEBAR

# Find the dependencies before checking for the component

find_package(GPCCHS_E_VIS-timeBar REQUIRED)

find_path(GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIR standaloneTimeBar/GPCCHS_E_VIS_StandaloneTimeBar.h
           dependencies/include
           NO_DEFAULT_PATH
           NO_CMAKE_ENVIRONMENT_PATH
           NO_CMAKE_PATH
           NO_SYSTEM_ENVIRONMENT_PATH
           NO_CMAKE_SYSTEM_PATH
          )

find_library(GPCCHSEVISSTANDALONETIMEBAR_LIBRARY ${CMAKE_SHARED_LIBRARY_PREFIX}gpcchs_e_vis_standaloneTimeBar${CMAKE_SHARED_LIBRARY_SUFFIX}.${GPCCHS_VERSION}
              dependencies/lib/so
              NO_DEFAULT_PATH
              NO_CMAKE_ENVIRONMENT_PATH
              NO_CMAKE_PATH
              NO_SYSTEM_ENVIRONMENT_PATH
              NO_CMAKE_SYSTEM_PATH
             )

set (GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIRS ${GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIR})
set (GPCCHSEVISSTANDALONETIMEBAR_LIBRARIES ${GPCCHSEVISSTANDALONETIMEBAR_LIBRARY})

set (ISIS_LIBRARIES ${GPCCHSEVISSTANDALONETIMEBAR_LIBRARIES} ${ISIS_LIBRARIES})
set (ISIS_INCLUDES ${GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIRS} ${ISIS_INCLUDES})

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set GPCCHSEVISSTANDALONETIMEBAR_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(GPCCHSEVISSTANDALONETIMEBAR DEFAULT_MSG GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIRS GPCCHSEVISSTANDALONETIMEBAR_LIBRARIES)

if ( GPCCHSEVISSTANDALONETIMEBAR_FOUND )
     MESSAGE (STATUS, "GPCCHS-E-VIS STANDALONETIMEBAR Found")
endif ()

mark_as_advanced(GPCCHSEVISSTANDALONETIMEBAR_INCLUDE_DIR GPCCHSEVISSTANDALONETIMEBAR_LIBRARY )

