stages:
  - build
  - test
  - slack_notif

image: node:6.3.0

variables:
  GIT_STRATEGY: none

cache:
  untracked: true
  paths:
    - node_modules/
  key: "node_modules"

job_build:
    stage: build
    script:
  - RUNNER_TOKEN=23659357- export RSA_WORKSPACE=/home_local/sduchesn/builds/$RUNNER_TOKEN/0/root/LPISIS
  - BUILD_DIR=/home_local/sduchesn/builds/$RUNNER_TOKEN/0/root/LPISIS/vima/$CI_COMMIT_REF_SLUG
  - echo $BUILD_DIR
  - CHECKOUT_DIR=$BUILD_DIR/build
  - NODE_MODULES=$BUILD_DIR/node_modules
  - echo $CHECKOUT_DIR
  - rm -rf $CHECKOUT_DIR
  - mkdir -p $CHECKOUT_DIR
  - echo $NODE_MODULES
  - mkdir -p $NODE_MODULES
  - cd $CHECKOUT_DIR
  - git clone git@isisdev153.cnes-isis.toulouse.atos.net:root/vima.git
  - cd $CHECKOUT_DIR/vima/GPCCHS_E_VIS/src/client/src/main/js/client
  - ln -s $NODE_MODULES node_modules
  - npm  run hello

job_lint:
  stage: test
  script:
   - RUNNER_TOKEN=23659357
   - BUILD_DIR=/home_local/sduchesn/builds/$RUNNER_TOKEN/0/root/LPISIS/vima/$CI_COMMIT_REF_SLUG
   - echo $BUILD_DIR
   - CHECKOUT_DIR=$BUILD_DIR/build
   - cd $CHECKOUT_DIR/vima/GPCCHS_E_VIS/src/client/src/main/js/client
   - npm run lint

job_test_coverage:
  stage: test
  script:
   - RUNNER_TOKEN=23659357
   - BUILD_DIR=/home_local/sduchesn/builds/$RUNNER_TOKEN/0/root/LPISIS/vima/$CI_COMMIT_REF_SLUG
   - echo $BUILD_DIR
   - CHECKOUT_DIR=$BUILD_DIR/build
   - cd $CHECKOUT_DIR/vima/GPCCHS_E_VIS/src/client/src/main/js/client
   - npm run test:coverage

job_slack_notif:
    stage: slack_notif
    script:
        - >-
            curl
            -x http://193.56.47.8:8080
            -X POST
            --data-urlencode "payload={\"channel\": \"#gitlab\", \"username\": \"CI - $GITLAB_USER_LOGIN\", \"text\": \" $GITLAB_USER_LOGIN tu fais que de la merde ! :poop: :poop: \nJob failed . \n<http://isisdev153.cnes-isis.toulouse.atos.net/root/vima/pipelines/$CI_PIPELINE_ID|Go to pipeline result>.\", \"icon_emoji\": \":avatar_$GITLAB_USER_ID:\"}"
            https://hooks.slack.com/services/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
    when: on_failure

job_validate_viewconf:
    stage: test
    script:
    - npm run test:validateViewConfigurationFiles -- ./data
