
export const LIFECYCLE_NOT_STARTED = 'LIFECYCLE_NOT_STARTED';
export const LIFECYCLE_CONNECTED_WITH_HSS = 'LIFECYCLE_CONNECTED_WITH_HSS';
export const LIFECYCLE_READY = 'LIFECYCLE_READY';
export const LIFECYCLE_STARTED = 'LIFECYCLE_STARTED';
export const ERRORTYPE_RESPONSE = 0;
