/**
 * Namespaces: HSC, HSS, WS
 * Domains: WINDOW, PAGE, VIEW, CD, EDITOR
 * Verbs: ADD, REMOVE, UN/MOUNT, UPDATE, OPEN, CLOSE
 */

export const HSC_UPDATE_STATUS = 'HSC_UPDATE_STATUS';
export const HSS_WS_REMOVE = 'HSS_WS_REMOVE';
export const HSS_WS_UPDATE_STATUS = 'HSS_WS_UPDATE_STATUS';
export const HSS_UPDATE_DOMAINS = 'HSS_UPDATE_DOMAINS';

export const WS_TIMEBAR_ADD = 'WS_TIMEBAR_ADD';
export const WS_TIMEBAR_REMOVE = 'WS_TIMEBAR_REMOVE';
export const WS_TIMEBAR_ID_UPDATE = 'WS_TIMEBAR_ID_UPDATE';
export const WS_TIMEBAR_VISUWINDOW_UPDATE = 'WS_TIMEBAR_VISUWINDOW_UPDATE';
export const WS_TIMEBAR_SPEED_UPDATE = 'WS_TIMEBAR_SPEED_UPDATE';
export const WS_TIMEBAR_PLAYINGSTATE_UPDATE = 'WS_TIMEBAR_PLAYINGSTATE_UPDATE';
export const WS_TIMEBAR_MASTERID_UPDATE = 'WS_TIMEBAR_MASTERID_UPDATE';
export const WS_TIMEBAR_MOUNT_TIMELINE = 'WS_TIMEBAR_ADDANDMOUNT_TIMELINE';
export const WS_TIMEBAR_UNMOUNT_TIMELINE = 'WS_TIMEBAR_REMOVEANDUNMOUNT_TIMELINE';
export const WS_TIMELINE_ADD = 'WS_TIMELINE_ADD';
export const WS_TIMELINE_REMOVE = 'WS_TIMELINE_REMOVE';
export const WS_TIMELINE_UPDATE_ID = 'WS_TIMELINE_UPDATE_ID';
export const WS_TIMELINE_UPDATE_NAME = 'WS_TIMELINE_UPDATE_NAME';
export const WS_TIMELINE_UPDATE_OFFSET = 'WS_TIMELINE_UPDATE_OFFSET';
export const WS_TIMELINE_UPDATE_SESSIONID = 'WS_TIMELINE_UPDATE_SESSIONID';
export const WS_WINDOW_ADD = 'WS_WINDOW_ADD';
export const WS_WINDOW_REMOVE = 'WS_WINDOW_REMOVE';
export const WS_WINDOW_UPDATE_GEOMETRY = 'WS_WINDOW_UPDATE_GEOMETRY';
export const WS_WINDOW_PAGE_FOCUS = 'WS_WINDOW_PAGE_FOCUS';
export const WS_WINDOW_PAGE_REORDER = 'WS_WINDOW_PAGE_REORDER';
export const WS_WINDOW_PAGE_MOUNT = 'WS_WINDOW_PAGE_MOUNT';
export const WS_WINDOW_PAGE_UNMOUNT = 'WS_WINDOW_PAGE_UNMOUNT';
export const WS_PAGE_ADD = 'WS_PAGE_ADD';
export const WS_PAGE_REMOVE = 'WS_PAGE_REMOVE';
export const WS_PAGE_UPDATE_LAYOUT = 'WS_PAGE_UPDATE_LAYOUT';
export const WS_PAGE_VIEW_MOUNT = 'WS_PAGE_VIEW_MOUNT';
export const WS_PAGE_VIEW_UNMOUNT = 'WS_PAGE_VIEW_UNMOUNT';
export const WS_PAGE_EDITOR_OPEN = 'WS_PAGE_EDITOR_OPEN';
export const WS_PAGE_EDITOR_CLOSE = 'WS_PAGE_EDITOR_CLOSE';
export const WS_VIEW_ADD = 'WS_VIEW_ADD';
export const WS_VIEW_REMOVE = 'WS_VIEW_REMOVE';
export const WS_VIEW_CD_MOUNT = 'WS_VIEW_CD_MOUNT';
export const WS_VIEW_CD_UNMOUNT = 'WS_VIEW_CD_UNMOUNT';

export const DATA_ADD_REQUESTS = 'DATA_ADD_REQUESTS';
export const DATA_REMOVE_REQUESTS = 'DATA_REMOVE_REQUESTS';
export const DATA_IMPORT_ONE_PAYLOAD = 'DATA_IMPORT_ONE_PAYLOAD';
export const DATA_IMPORT_RANGE_PAYLOADS = 'DATA_IMPORT_RANGE_PAYLOADS';
