import _each from 'lodash/each';

const isParameterSupported = require('./isParameterSupported');


const comObjects = {
  COP1Context: [
    { catalog: '', parameterName: '', comObject: 'COP1Context', shouldBe: true },
    { catalog: 'undefined', parameterName: '', comObject: 'COP1Context', shouldBe: true },
    { catalog: '', parameterName: 'undefined', comObject: 'COP1Context', shouldBe: true },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'COP1Context', shouldBe: true },
  ],
  decommutedPacket: [
    { catalog: '', parameterName: '', comObject: 'DecommutedPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'DecommutedPacket', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'DecommutedPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'DecommutedPacket', shouldBe: false },
    { catalog: 'TelemetryPacket', parameterName: '', comObject: 'DecommutedPacket', shouldBe: true },
    { catalog: 'TelemetryPacket', parameterName: 'undefined', comObject: 'DecommutedPacket', shouldBe: true },
  ],
  ClcwPacket: [
    { catalog: '', parameterName: '', comObject: 'ClcwPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'ClcwPacket', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'ClcwPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'ClcwPacket', shouldBe: false },
    { catalog: 'TelemetryPacket', parameterName: '', comObject: 'ClcwPacket', shouldBe: true },
    { catalog: 'TelemetryPacket', parameterName: 'undefined', comObject: 'ClcwPacket', shouldBe: true },
  ],
  IsisAggregation: [
    { catalog: '', parameterName: '', comObject: 'IsisAggregation', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'IsisAggregation', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'IsisAggregation', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'IsisAggregation', shouldBe: false },
    { catalog: 'TelemetryPacket', parameterName: '', comObject: 'IsisAggregation', shouldBe: true },
    { catalog: 'TelemetryPacket', parameterName: 'undefined', comObject: 'IsisAggregation', shouldBe: true },
  ],
  RmPacket: [
    { catalog: '', parameterName: '', comObject: 'RmPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'RmPacket', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'RmPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'RmPacket', shouldBe: false },
    { catalog: 'TelemetryPacket', parameterName: '', comObject: 'RmPacket', shouldBe: true },
    { catalog: 'TelemetryPacket', parameterName: 'undefined', comObject: 'RmPacket', shouldBe: true },
  ],
  TmPacket: [
    { catalog: '', parameterName: '', comObject: 'TmPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'TmPacket', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'TmPacket', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'TmPacket', shouldBe: false },
    { catalog: 'TelemetryPacket', parameterName: '', comObject: 'TmPacket', shouldBe: true },
    { catalog: 'TelemetryPacket', parameterName: 'undefined', comObject: 'TmPacket', shouldBe: true },
  ],
  ReportingParameter: [
    { catalog: '', parameterName: '', comObject: 'ReportingParameter', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'ReportingParameter', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'ReportingParameter', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'ReportingParameter', shouldBe: false },
    { catalog: 'Reporting', parameterName: '', comObject: 'ReportingParameter', shouldBe: true },
    { catalog: 'Reporting', parameterName: 'undefined', comObject: 'ReportingParameter', shouldBe: true },
  ],
  GroundMonitoringAlarmAckRequest: [
    { catalog: '', parameterName: '', comObject: 'GroundMonitoringAlarmAckRequest', shouldBe: true },
    { catalog: 'undefined', parameterName: '', comObject: 'GroundMonitoringAlarmAckRequest', shouldBe: true },
    { catalog: '', parameterName: 'undefined', comObject: 'GroundMonitoringAlarmAckRequest', shouldBe: true },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'GroundMonitoringAlarmAckRequest', shouldBe: true },
  ],
  GroundMonitoringAlarm: [
    { catalog: '', parameterName: '', comObject: 'GroundMonitoringAlarm', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'GroundMonitoringAlarm', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'GroundMonitoringAlarm', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'GroundMonitoringAlarm', shouldBe: false },
    { catalog: 'Monitoring', parameterName: '', comObject: 'GroundMonitoringAlarm', shouldBe: true },
    { catalog: 'Monitoring', parameterName: 'undefined', comObject: 'GroundMonitoringAlarm', shouldBe: true },
  ],
  OnBoardAlarmAckRequest: [
    { catalog: '', parameterName: '', comObject: 'OnBoardAlarmAckRequest', shouldBe: true },
    { catalog: 'undefined', parameterName: '', comObject: 'OnBoardAlarmAckRequest', shouldBe: true },
    { catalog: '', parameterName: 'undefined', comObject: 'OnBoardAlarmAckRequest', shouldBe: true },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'OnBoardAlarmAckRequest', shouldBe: true },
  ],
  OperationParameter: [
    { catalog: '', parameterName: '', comObject: 'OperationParameter', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'OperationParameter', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'OperationParameter', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'OperationParameter', shouldBe: false },
    { catalog: 'OperationParameter', parameterName: '', comObject: 'OperationParameter', shouldBe: true },
    { catalog: 'OperationParameter', parameterName: 'undefined', comObject: 'OperationParameter', shouldBe: true },
  ],
  ComputedEvent: [
    { catalog: '', parameterName: '', comObject: 'ComputedEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'ComputedEvent', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'ComputedEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'ComputedEvent', shouldBe: false },
    { catalog: 'ComputedEventDefinition', parameterName: '', comObject: 'ComputedEvent', shouldBe: true },
    { catalog: 'ComputedEventDefinition', parameterName: 'undefined', comObject: 'ComputedEvent', shouldBe: true },
  ],
  LogbookEvent: [
    { catalog: '', parameterName: '', comObject: 'LogbookEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'LogbookEvent', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'LogbookEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'LogbookEvent', shouldBe: false },
    { catalog: 'LogbookEventDefinition', parameterName: '', comObject: 'LogbookEvent', shouldBe: true },
    { catalog: 'LogbookEventDefinition', parameterName: 'undefined', comObject: 'LogbookEvent', shouldBe: true },
  ],
  ExternalEvent: [
    { catalog: '', parameterName: '', comObject: 'ExternalEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'ExternalEvent', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'ExternalEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'ExternalEvent', shouldBe: false },
    { catalog: 'UserEventDefinition', parameterName: '', comObject: 'ExternalEvent', shouldBe: true },
    { catalog: 'UserEventDefinition', parameterName: 'undefined', comObject: 'ExternalEvent', shouldBe: true },
  ],
  UserEvent: [
    { catalog: '', parameterName: '', comObject: 'UserEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'UserEvent', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'UserEvent', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'UserEvent', shouldBe: false },
    { catalog: 'UserEventDefinition', parameterName: '', comObject: 'UserEvent', shouldBe: true },
    { catalog: 'UserEventDefinition', parameterName: 'undefined', comObject: 'UserEvent', shouldBe: true },
  ],
  Pus003Model: [
    { catalog: '', parameterName: '', comObject: 'Pus003Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus003Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus003Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus003Model', shouldBe: false },
    { catalog: 'Pus003', parameterName: 'parameter', comObject: 'Pus003Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus003Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus003Model', shouldBe: true },
  ],
  Pus005Model: [
    { catalog: '', parameterName: '', comObject: 'Pus005Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus005Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus005Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus005Model', shouldBe: false },
    { catalog: 'Pus005', parameterName: 'parameter', comObject: 'Pus005Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus005Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus005Model', shouldBe: true },
  ],
  Pus012Model: [
    { catalog: '', parameterName: '', comObject: 'Pus012Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus012Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus012Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus012Model', shouldBe: false },
    { catalog: 'Pus012', parameterName: 'parameter', comObject: 'Pus012Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus012Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus012Model', shouldBe: true },
  ],
  Pus011Command: [
    { catalog: '', parameterName: '', comObject: 'Pus011Command', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus011Command', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus011Command', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus011Command', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus011Command', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus011Command', shouldBe: true },
  ],
  Pus011Model: [
    { catalog: '', parameterName: '', comObject: 'Pus011Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus011Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus011Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus011Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus011Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus011Model', shouldBe: true },
  ],
  Pus011SubSchedule: [
    { catalog: '', parameterName: '', comObject: 'Pus011SubSchedule', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus011SubSchedule', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus011SubSchedule', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus011SubSchedule', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus011SubSchedule', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus011SubSchedule', shouldBe: true },
  ],
  Pus011SyncPoint: [
    { catalog: '', parameterName: '', comObject: 'Pus011SyncPoint', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus011SyncPoint', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus011SyncPoint', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus011SyncPoint', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus011SyncPoint', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus011SyncPoint', shouldBe: true },
  ],
  Pus013Model: [
    { catalog: '', parameterName: '', comObject: 'Pus013Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus013Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus013Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus013Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus013Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus013Model', shouldBe: true },
  ],
  Pus014Model: [
    { catalog: '', parameterName: '', comObject: 'Pus014Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus014Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus014Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus014Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus014Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus014Model', shouldBe: true },
  ],
  Pus015Model: [
    { catalog: '', parameterName: '', comObject: 'Pus015Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus015Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus015Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus015Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus015Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus015Model', shouldBe: true },
  ],
  Pus018Model: [
    { catalog: '', parameterName: '', comObject: 'Pus018Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus018Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus018Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus018Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus018Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus018Model', shouldBe: true },
  ],
  Pus019Model: [
    { catalog: '', parameterName: '', comObject: 'Pus019Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus019Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus019Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus019Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus019Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus019Model', shouldBe: true },
  ],
  Pus140Model: [
    { catalog: '', parameterName: '', comObject: 'Pus140Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus140Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus140Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus140Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus140Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus140Model', shouldBe: true },
  ],
  Pus142Model: [
    { catalog: '', parameterName: '', comObject: 'Pus142Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus142Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus142Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus142Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus142Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus142Model', shouldBe: true },
  ],
  Pus144Model: [
    { catalog: '', parameterName: '', comObject: 'Pus144Model', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'Pus144Model', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'Pus144Model', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'Pus144Model', shouldBe: false },
    { catalog: 'PusGroundModelDefinition', parameterName: '', comObject: 'Pus144Model', shouldBe: true },
    { catalog: 'PusGroundModelDefinition', parameterName: 'undefined', comObject: 'Pus144Model', shouldBe: true },
  ],
  StatAggregation: [
    { catalog: '', parameterName: '', comObject: 'StatAggregation', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'StatAggregation', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'StatAggregation', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'StatAggregation', shouldBe: false },
    { catalog: 'StatAggregationDefinition', parameterName: '', comObject: 'StatAggregation', shouldBe: true },
    { catalog: 'StatAggregationDefinition', parameterName: 'undefined', comObject: 'StatAggregation', shouldBe: true },
  ],
  StatValue: [
    { catalog: '', parameterName: '', comObject: 'StatValue', shouldBe: false },
    { catalog: 'undefined', parameterName: '', comObject: 'StatValue', shouldBe: false },
    { catalog: '', parameterName: 'undefined', comObject: 'StatValue', shouldBe: false },
    { catalog: 'undefined', parameterName: 'undefined', comObject: 'StatValue', shouldBe: false },
    { catalog: 'StatValuesDefinition', parameterName: '', comObject: 'StatValue', shouldBe: true },
    { catalog: 'StatValuesDefinition', parameterName: 'undefined', comObject: 'StatValue', shouldBe: true },
  ],
};

describe('isParameterSupported', () => {
  _each(comObjects, (comObject, key) => {
    describe(`isParameterSupported :: ${key}`, () => {
      _each(comObject, (t) => {
        test(`${t.catalog}.${t.parameterName}<${t.comObject}> should be ${t.shouldBe}`, () => {
          expect(isParameterSupported(t)).toEqual(t.shouldBe);
        });
      });
    });
  });
});

