/* eslint-disable no-unused-vars */
const initialState = {
  onBoardEvents: {
    data: [
      {
        baz: 'baz',
        onBoardStatus: 'DISABLED',
        defaultOnBoardStatus: 'DISABLED',
        lastUpdateModeRid: 'TC',
        lastUpdateModeOnBoardStatus: 'TC',
        lastUpdateModeAlarmLevel: 'TC',
      },
      {
        baz: 'baz',
        onBoardStatus: 'ENABLED',
        defaultOnBoardStatus: 'ENABLED',
        lastUpdateModeRid: 'TM',
        lastUpdateModeOnBoardStatus: 'TM',
        lastUpdateModeAlarmLevel: 'TM',
      },
    ],
  },
  received: {
    data: [
      {
        baz: 'baz1',
        name1: 'name1',
        value1: 'value',
        name2: 'name2',
        value2: 'value',
        name3: 'name3',
        value3: 'value',
        name4: 'name4',
        value4: 'value',
        name5: 'name5',
        value5: 'value',
        name6: 'name6',
        value6: 'value',
        name7: 'name7',
        value7: 'value',
        name8: 'name8',
        value8: 'value',
        name9: 'name9',
        value9: 'value',
        name10: 'name10',
        value10: 'value',
      },
      {
        baz: 'baz2',
        name1: 'name1',
        value1: 'value',
        name2: 'name2',
        value2: 'value',
        name3: 'name3',
        value3: 'value',
        name4: 'name4',
        value4: 'value',
        name5: 'name5',
        value5: 'value',
        name6: 'name6',
        value6: 'value',
        name7: 'name7',
        value7: 'value',
        name8: 'name8',
        value8: 'value',
        name9: 'name9',
        value9: 'value',
        name10: 'name10',
        value10: 'value',
      },
    ],
  },
};
