module.exports = {
  encode: data => ({
    scdCop1Ack: data.scdCop1Ack,
    cop1Ack: data.cop1Ack,
    stationAck: data.stationAck,
    missionFailure: data.missionFailure,
    executionComplete: data.executionComplete,
    acceptance: data.acceptance,
    scdCop1AckRcvDate: { value: data.scdCop1AckRcvDate },
    Cop1AckRcvDate: { value: data.Cop1AckRcvDate },
    stationAckRcvDate: { value: data.stationAckRcvDate },
    missionFailureRcvDate: { value: data.missionFailureRcvDate },
    executionCompleteRcvDate: { value: data.executionCompleteRcvDate },
    acceptanceRcvDate: { value: data.acceptanceRcvDate },
    executionStartRcvDate: { value: data.executionStartRcvDate },
    executionStart: data.executionStart,
  }),
  decode: data => ({
    scdCop1Ack: data.scdCop1Ack,
    cop1Ack: data.cop1Ack,
    stationAck: data.stationAck,
    missionFailure: data.missionFailure,
    executionComplete: data.executionComplete,
    acceptance: data.acceptance,
    scdCop1AckRcvDate: data.scdCop1AckRcvDate.value.toNumber(),
    Cop1AckRcvDate: data.Cop1AckRcvDate.value.toNumber(),
    stationAckRcvDate: data.stationAckRcvDate.value.toNumber(),
    missionFailureRcvDate: data.missionFailureRcvDate.value.toNumber(),
    executionCompleteRcvDate: data.executionCompleteRcvDate.value.toNumber(),
    acceptanceRcvDate: data.acceptanceRcvDate.value.toNumber(),
    executionStartRcvDate: data.executionStartRcvDate.value.toNumber(),
    executionStart: data.executionStart,
  }),
};
